name: Deploy to DEV Oracle Cloud

on:
  push:
    branches:
      - main_dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive needed files
        run: |
          tar --exclude='.git' \
              --exclude='.github' \
              --exclude='node_modules' \
              --exclude='*.log' \
              -czf app.tar.gz .

      - name: Upload archive via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "app.tar.gz"
          target: "/home/ubuntu/proyectoSoftwere/dev"

      - name: SSH deploy & extract
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/proyectoSoftwere/dev
            rm -rf backend
            mkdir -p backend
            tar -xzf app.tar.gz -C backend
            rm app.tar.gz
            docker compose build
            docker compose up -d
